import Head from "next/head";
import Link from "next/link";
import { useTranslation } from "react-i18next";

// import menus
import { menus } from "@/common/data";

// import components
import { Layout, Layout1, Button, Badge } from "@/components";

// import styles
import variables from "@/assets/scss/variables.module.scss";
import styles from "@/assets/scss/pages/Index.module.scss";

export default function Index() {
  const { t, i18n } = useTranslation();

  const changeLanguageAction = (lng) => {
    // set the selected language to i18n
    i18n.changeLanguage(lng);
  };

  return (
    <>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.index}>
        <ul style={{ display: "flex" }}>
          <li style={{ marginRight: 15 }}>
            <button onClick={() => changeLanguageAction("en")}>
              {t("en")}
            </button>
          </li>
          <li style={{ marginRight: 15 }}>
            <button onClick={() => changeLanguageAction("de")}>
              {t("de")}
            </button>
          </li>
          <li style={{ marginRight: 15 }}>
            <button onClick={() => changeLanguageAction("fr")}>
              {t("fr")}
            </button>
          </li>
          <li style={{ marginRight: 15 }}>
            <button onClick={() => changeLanguageAction("it")}>
              {t("it")}
            </button>
          </li>
          <li style={{ marginRight: 15 }}>
            <button onClick={() => changeLanguageAction("es")}>
              {t("es")}
            </button>
          </li>
          <li style={{ marginRight: 15 }}>
            <button onClick={() => changeLanguageAction("it")}>
              {t("it")}
            </button>
          </li>
          <li style={{ marginRight: 15 }}>
            <button onClick={() => changeLanguageAction("tr")}>
              {t("tr")}
            </button>
          </li>
        </ul>
      </main>
    </>
  );
}

Index.getLayout = function getLayout(page) {
  return (
    <Layout color={variables.primaryColor}>
      <Layout1>{page}</Layout1>
    </Layout>
  );
};
